@startuml
actor joueur << actor >>
agent jeu
jeu --> joueur : Informations ressources /joueur

joueur --> jeu :  - Acheter/Améliorer/Récolter Extracteur \n- Informations ressources / joueur

joueur -- jeu
@enduml