@startuml
'https://plantuml.com/sequence-diagram

actor __player__

__player__ -> "__extractorRegistry__ : ExtractorRegistry" : getExtractorsPrototype
activate __player__

activate "__extractorRegistry__ : ExtractorRegistry"

__player__ -> "__extractorRegistry__ : ExtractorRegistry" : getExtractorPrototypeById(4)
__player__ <-- "__extractorRegistry__ : ExtractorRegistry" : extractorPrototype

__player__ -> "__level__ : PlayerLevel" : <<create()>>
activate "__level__ : PlayerLevel"
deactivate "__level__ : PlayerLevel"

@enduml